-- Generated by nwg-displays on 2026-08-04 at 21:00:03. Do not edit manually.

hl.monitor({
    output = "desc:HP Inc. HP 27f 3CM0431S0N",
    mode = "1920x1080@60.0",
    position = "1200x0",
    scale = 1.0
})
hl.monitor({
    output = "desc:Hewlett Packard HP ZR2440w CN43520BBL",
    mode = "1920x1200@59.95",
    position = "0x0",
    scale = 1.0,
    transform = 1
})
