-- Generated by nwg-displays on 2026-08-18 at 16:35:25. Do not edit manually.

hl.workspace_rule({
    workspace = "1",
    monitor = "desc:Samsung Electric Company Odyssey G5 HNMY502830",
    default = true
})
hl.workspace_rule({
    workspace = "2",
    monitor = "desc:Samsung Electric Company Odyssey G5 HNMY502830"
})
hl.workspace_rule({
    workspace = "3",
    monitor = "desc:Samsung Electric Company Odyssey G5 HNMY502830"
})
hl.workspace_rule({
    workspace = "4",
    monitor = "desc:Samsung Electric Company Odyssey G5 HNMY502830"
})
hl.workspace_rule({
    workspace = "5",
    monitor = "desc:Samsung Electric Company Odyssey G5 HNMY502830"
})
hl.workspace_rule({
    workspace = "6",
    monitor = "desc:Samsung Electric Company Odyssey G5 HNMY502830"
})
hl.workspace_rule({
    workspace = "7",
    monitor = "desc:Samsung Electric Company Odyssey G5 HNMY502830"
})
hl.workspace_rule({
    workspace = "8",
    monitor = "desc:Hewlett Packard HP ZR2440w CN43520BBL",
    default = true
})
hl.workspace_rule({
    workspace = "9",
    monitor = "desc:Hewlett Packard HP ZR2440w CN43520BBL"
})
hl.workspace_rule({
    workspace = "10",
    monitor = "desc:Hewlett Packard HP ZR2440w CN43520BBL"
})
