[[manager.prepend_keymap]]
on   = [ "g", "w" ]
run  = "cd /home/Arieldynamic/GOOGLE-DRIVE/School-Drive/4_TAMU_Files/6_Spring_2025_Semester_Files"
desc = "Go to WORK_DIR"

[[manager.prepend_keymap]]
on   = [ "g", "t"]
run  = "cd /home/Arieldynamic/.local/share/Trash/"
desc = "Go to TRASH"

[[manager.prepend_keymap]]
on  = "M"
run = "plugin mount"

[[manager.prepend_keymap]]
on   = "!"
run  = 'shell "$SHELL" --block'
desc = "Open shell here"
